language: node_js
node_js:
- 7.8.0
after_success:
- npm run coveralls
install:
- npm install
script: npm run build:travis
deploy:
  provider: bintray
  file: bintray.json
  user: rkorytkowski
  key: $BINTRAY_API_KEY
  dry-run: false
  on:
    tags: true
